name: SAST - Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  SAST:
    name: SAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para SonarCloud

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN  }}

      - name: SonarCloud Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Validando resultados de SonarCloud
        run: |
          echo "Esperando resultados del análisis en SonarCloud..."

          # Esperar a que el análisis se procese (máximo 60s)
          for i in {1..12}; do
            response=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}")
            status=$(echo "$response" | jq -r '.projectStatus.status')

            if [[ "$status" == "OK" || "$status" == "WARN" || "$status" == "ERROR" ]]; then
              echo "Estado del Quality Gate: $status"
              break
            fi

            echo "Aún no disponible (status: $status), esperando 5s..."
            sleep 5
          done

          # Validar estado final
          case "$status" in
            "OK")
              echo "✔️ Calidad del código: OK"
              ;;
            "WARN")
              echo "⚠️ Calidad del código: WARN"
              exit 1
              ;;
            "ERROR")
              echo "❌ Calidad del código: ERROR"
              exit 1
              ;;
            *)
              echo "❓ Estado desconocido del Quality Gate: $status"
              exit 1
              ;;
          esac
