name: Docker Build

on:
  workflow_run:
    workflows: ["SCA - Dependency-Check"]
    types:
      - completed

jobs:
  DockerBuild:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kratos32/labFinalDevSecOps:latest
